"""S&P 500 constituent seeds (generated 2026-09-17).

Source: Wikipedia "List of S&P 500 companies" (symbols/names/sectors)
crossed with Nasdaq Trader symbol directories (nasdaqlisted/otherlisted)
for NYSE vs Nasdaq venue mapping. Regenerate with the one-shot script
when the index changes; keep sorted by symbol. Identity stays
(exchange_mic, exchange_symbol) like all registry seeds.
"""

from __future__ import annotations

# (exchange_symbol, company_name, sector, exchange_mic)
SP500_MEMBERS: list[tuple[str, str, str, str]] = [
    ("A", "Agilent Technologies", "Healthcare", "XNYS"),
    ("AAPL", "Apple Inc.", "Technology", "XNAS"),
    ("ABBV", "AbbVie", "Healthcare", "XNYS"),
    ("ABNB", "Airbnb", "Consumer Cyclical", "XNAS"),
    ("ABT", "Abbott Laboratories", "Healthcare", "XNYS"),
    ("ACGL", "Arch Capital Group", "Financial Services", "XNAS"),
    ("ACN", "Accenture", "Technology", "XNYS"),
    ("ADBE", "Adobe Inc.", "Technology", "XNAS"),
    ("ADI", "Analog Devices", "Technology", "XNAS"),
    ("ADM", "Archer Daniels Midland", "Consumer Defensive", "XNYS"),
    ("ADP", "Automatic Data Processing", "Industrials", "XNAS"),
    ("ADSK", "Autodesk", "Technology", "XNAS"),
    ("AEE", "Ameren", "Utilities", "XNYS"),
    ("AEP", "American Electric Power", "Utilities", "XNAS"),
    ("AES", "AES Corporation", "Utilities", "XNYS"),
    ("AFL", "Aflac", "Financial Services", "XNYS"),
    ("AIG", "American International Group", "Financial Services", "XNYS"),
    ("AIZ", "Assurant", "Financial Services", "XNYS"),
    ("AJG", "Arthur J. Gallagher & Co.", "Financial Services", "XNYS"),
    ("AKAM", "Akamai Technologies", "Technology", "XNAS"),
    ("ALB", "Albemarle Corporation", "Materials", "XNYS"),
    ("ALGN", "Align Technology", "Healthcare", "XNAS"),
    ("ALL", "Allstate", "Financial Services", "XNYS"),
    ("ALLE", "Allegion", "Industrials", "XNYS"),
    ("AMAT", "Applied Materials", "Technology", "XNAS"),
    ("AMCR", "Amcor", "Materials", "XNYS"),
    ("AMD", "Advanced Micro Devices", "Technology", "XNAS"),
    ("AME", "Ametek", "Industrials", "XNYS"),
    ("AMGN", "Amgen", "Healthcare", "XNAS"),
    ("AMP", "Ameriprise Financial", "Financial Services", "XNYS"),
    ("AMT", "American Tower", "Real Estate", "XNYS"),
    ("AMZN", "Amazon", "Consumer Cyclical", "XNAS"),
    ("ANET", "Arista Networks", "Technology", "XNYS"),
    ("AON", "Aon plc", "Financial Services", "XNYS"),
    ("AOS", "A. O. Smith", "Industrials", "XNYS"),
    ("APA", "APA Corporation", "Energy", "XNAS"),
    ("APD", "Air Products", "Materials", "XNYS"),
    ("APH", "Amphenol", "Technology", "XNYS"),
    ("APO", "Apollo Global Management", "Financial Services", "XNYS"),
    ("APP", "AppLovin", "Communication", "XNAS"),
    ("APTV", "Aptiv", "Consumer Cyclical", "XNYS"),
    ("ARE", "Alexandria Real Estate Equities", "Real Estate", "XNYS"),
    ("ARES", "Ares Management", "Financial Services", "XNYS"),
    ("ATO", "Atmos Energy", "Utilities", "XNYS"),
    ("AVGO", "Broadcom", "Technology", "XNAS"),
    ("AVY", "Avery Dennison", "Materials", "XNYS"),
    ("AWK", "American Water Works", "Utilities", "XNYS"),
    ("AXON", "Axon Enterprise", "Industrials", "XNAS"),
    ("AXP", "American Express", "Financial Services", "XNYS"),
    ("AZO", "AutoZone", "Consumer Cyclical", "XNYS"),
    ("BA", "Boeing", "Industrials", "XNYS"),
    ("BAC", "Bank of America", "Financial Services", "XNYS"),
    ("BALL", "Ball Corporation", "Materials", "XNYS"),
    ("BAX", "Baxter International", "Healthcare", "XNYS"),
    ("BBY", "Best Buy", "Consumer Cyclical", "XNYS"),
    ("BDX", "Becton Dickinson", "Healthcare", "XNYS"),
    ("BEN", "Franklin Resources", "Financial Services", "XNYS"),
    ("BF.B", "Brown–Forman", "Consumer Defensive", "XNYS"),
    ("BG", "Bunge Global", "Consumer Defensive", "XNYS"),
    ("BIIB", "Biogen", "Healthcare", "XNAS"),
    ("BKNG", "Booking Holdings", "Consumer Cyclical", "XNAS"),
    ("BKR", "Baker Hughes", "Energy", "XNAS"),
    ("BLDR", "Builders FirstSource", "Industrials", "XNYS"),
    ("BLK", "BlackRock", "Financial Services", "XNYS"),
    ("BMY", "Bristol Myers Squibb", "Healthcare", "XNYS"),
    ("BNY", "BNY Mellon", "Financial Services", "XNYS"),
    ("BR", "Broadridge Financial Solutions", "Industrials", "XNYS"),
    ("BRK.B", "Berkshire Hathaway", "Financial Services", "XNYS"),
    ("BRO", "Brown & Brown", "Financial Services", "XNYS"),
    ("BSX", "Boston Scientific", "Healthcare", "XNYS"),
    ("BX", "Blackstone Inc.", "Financial Services", "XNYS"),
    ("BXP", "BXP, Inc.", "Real Estate", "XNYS"),
    ("C", "Citigroup", "Financial Services", "XNYS"),
    ("CAH", "Cardinal Health", "Healthcare", "XNYS"),
    ("CARR", "Carrier Global", "Industrials", "XNYS"),
    ("CASY", "Casey's", "Consumer Defensive", "XNAS"),
    ("CAT", "Caterpillar Inc.", "Industrials", "XNYS"),
    ("CB", "Chubb Limited", "Financial Services", "XNYS"),
    ("CBRE", "CBRE Group", "Real Estate", "XNYS"),
    ("CCI", "Crown Castle", "Real Estate", "XNYS"),
    ("CCL", "Carnival Corporation", "Consumer Cyclical", "XNYS"),
    ("CDNS", "Cadence Design Systems", "Technology", "XNAS"),
    ("CDW", "CDW Corporation", "Technology", "XNAS"),
    ("CEG", "Constellation Energy", "Utilities", "XNAS"),
    ("CF", "CF Industries", "Materials", "XNYS"),
    ("CFG", "Citizens Financial Group", "Financial Services", "XNYS"),
    ("CHD", "Church & Dwight", "Consumer Defensive", "XNYS"),
    ("CHRW", "C.H. Robinson", "Industrials", "XNAS"),
    ("CHTR", "Charter Communications", "Communication", "XNAS"),
    ("CI", "Cigna", "Healthcare", "XNYS"),
    ("CIEN", "Ciena", "Technology", "XNYS"),
    ("CINF", "Cincinnati Financial", "Financial Services", "XNAS"),
    ("CL", "Colgate-Palmolive", "Consumer Defensive", "XNYS"),
    ("CLX", "Clorox", "Consumer Defensive", "XNYS"),
    ("CMCSA", "Comcast", "Communication", "XNAS"),
    ("CME", "CME Group", "Financial Services", "XNAS"),
    ("CMG", "Chipotle Mexican Grill", "Consumer Cyclical", "XNYS"),
    ("CMI", "Cummins", "Industrials", "XNYS"),
    ("CMS", "CMS Energy", "Utilities", "XNYS"),
    ("CNC", "Centene Corporation", "Healthcare", "XNYS"),
    ("CNP", "CenterPoint Energy", "Utilities", "XNYS"),
    ("COF", "Capital One", "Financial Services", "XNYS"),
    ("COHR", "Coherent Corp.", "Technology", "XNYS"),
    ("COIN", "Coinbase", "Financial Services", "XNAS"),
    ("COO", "Cooper Companies (The)", "Healthcare", "XNAS"),
    ("COP", "ConocoPhillips", "Energy", "XNYS"),
    ("COR", "Cencora", "Healthcare", "XNYS"),
    ("COST", "Costco", "Consumer Defensive", "XNAS"),
    ("CPAY", "Corpay", "Financial Services", "XNYS"),
    ("CPRT", "Copart", "Industrials", "XNAS"),
    ("CPT", "Camden Property Trust", "Real Estate", "XNYS"),
    ("CRH", "CRH plc", "Materials", "XNYS"),
    ("CRL", "Charles River Laboratories", "Healthcare", "XNYS"),
    ("CRM", "Salesforce", "Technology", "XNYS"),
    ("CRWD", "CrowdStrike", "Technology", "XNAS"),
    ("CSCO", "Cisco", "Technology", "XNAS"),
    ("CSGP", "CoStar Group", "Real Estate", "XNAS"),
    ("CSX", "CSX Corporation", "Industrials", "XNAS"),
    ("CTAS", "Cintas", "Industrials", "XNAS"),
    ("CTSH", "Cognizant", "Technology", "XNAS"),
    ("CTVA", "Corteva", "Materials", "XNYS"),
    ("CVNA", "Carvana", "Consumer Cyclical", "XNYS"),
    ("CVS", "CVS Health", "Healthcare", "XNYS"),
    ("CVX", "Chevron Corporation", "Energy", "XNYS"),
    ("D", "Dominion Energy", "Utilities", "XNYS"),
    ("DAL", "Delta Air Lines", "Industrials", "XNYS"),
    ("DASH", "DoorDash", "Consumer Cyclical", "XNAS"),
    ("DD", "DuPont", "Industrials", "XNYS"),
    ("DDOG", "Datadog", "Technology", "XNAS"),
    ("DE", "Deere & Company", "Industrials", "XNYS"),
    ("DECK", "Deckers Brands", "Consumer Cyclical", "XNYS"),
    ("DELL", "Dell Technologies", "Technology", "XNYS"),
    ("DG", "Dollar General", "Consumer Defensive", "XNYS"),
    ("DGX", "Quest Diagnostics", "Healthcare", "XNYS"),
    ("DHI", "D. R. Horton", "Consumer Cyclical", "XNYS"),
    ("DHR", "Danaher Corporation", "Healthcare", "XNYS"),
    ("DIS", "Walt Disney Company (The)", "Communication", "XNYS"),
    ("DLR", "Digital Realty", "Real Estate", "XNYS"),
    ("DLTR", "Dollar Tree", "Consumer Defensive", "XNAS"),
    ("DOC", "Healthpeak Properties", "Real Estate", "XNYS"),
    ("DOV", "Dover Corporation", "Industrials", "XNYS"),
    ("DOW", "Dow Inc.", "Materials", "XNYS"),
    ("DPZ", "Domino's", "Consumer Cyclical", "XNAS"),
    ("DRI", "Darden Restaurants", "Consumer Cyclical", "XNYS"),
    ("DTE", "DTE Energy", "Utilities", "XNYS"),
    ("DUK", "Duke Energy", "Utilities", "XNYS"),
    ("DVA", "DaVita", "Healthcare", "XNYS"),
    ("DVN", "Devon Energy", "Energy", "XNYS"),
    ("DXCM", "Dexcom", "Healthcare", "XNAS"),
    ("EBAY", "eBay Inc.", "Consumer Cyclical", "XNAS"),
    ("ECHO", "EchoStar", "Communication", "XNAS"),
    ("ECL", "Ecolab", "Materials", "XNYS"),
    ("ED", "Consolidated Edison", "Utilities", "XNYS"),
    ("EFX", "Equifax", "Industrials", "XNYS"),
    ("EG", "Everest Group", "Financial Services", "XNYS"),
    ("EIX", "Edison International", "Utilities", "XNYS"),
    ("EL", "Estée Lauder Companies (The)", "Consumer Defensive", "XNYS"),
    ("ELV", "Elevance Health", "Healthcare", "XNYS"),
    ("EMR", "Emerson Electric", "Industrials", "XNYS"),
    ("EOG", "EOG Resources", "Energy", "XNYS"),
    ("EQIX", "Equinix", "Real Estate", "XNAS"),
    ("EQT", "EQT Corporation", "Energy", "XNYS"),
    ("ERIE", "Erie Indemnity", "Financial Services", "XNAS"),
    ("ES", "Eversource Energy", "Utilities", "XNYS"),
    ("ESS", "Essex Property Trust", "Real Estate", "XNYS"),
    ("ETN", "Eaton Corporation", "Industrials", "XNYS"),
    ("ETR", "Entergy", "Utilities", "XNYS"),
    ("EVRG", "Evergy", "Utilities", "XNAS"),
    ("EW", "Edwards Lifesciences", "Healthcare", "XNYS"),
    ("EXC", "Exelon", "Utilities", "XNAS"),
    ("EXE", "Expand Energy", "Energy", "XNAS"),
    ("EXPD", "Expeditors International", "Industrials", "XNYS"),
    ("EXPE", "Expedia Group", "Consumer Cyclical", "XNAS"),
    ("EXR", "Extra Space Storage", "Real Estate", "XNYS"),
    ("F", "Ford Motor Company", "Consumer Cyclical", "XNYS"),
    ("FANG", "Diamondback Energy", "Energy", "XNAS"),
    ("FAST", "Fastenal", "Industrials", "XNAS"),
    ("FCX", "Freeport-McMoRan", "Materials", "XNYS"),
    ("FDS", "FactSet", "Financial Services", "XNYS"),
    ("FDX", "FedEx", "Industrials", "XNYS"),
    ("FDXF", "FedEx Freight", "Industrials", "XNYS"),
    ("FE", "FirstEnergy", "Utilities", "XNYS"),
    ("FERG", "Ferguson Enterprises", "Industrials", "XNYS"),
    ("FFIV", "F5, Inc.", "Technology", "XNAS"),
    ("FICO", "Fair Isaac", "Technology", "XNYS"),
    ("FIS", "Fidelity National Information Services", "Financial Services", "XNYS"),
    ("FISV", "Fiserv", "Financial Services", "XNAS"),
    ("FITB", "Fifth Third Bancorp", "Financial Services", "XNYS"),
    ("FIX", "Comfort Systems USA", "Industrials", "XNYS"),
    ("FLEX", "Flex Ltd.", "Technology", "XNAS"),
    ("FOX", "Fox Corporation (Class B)", "Communication", "XNAS"),
    ("FOXA", "Fox Corporation (Class A)", "Communication", "XNAS"),
    ("FRT", "Federal Realty Investment Trust", "Real Estate", "XNYS"),
    ("FSLR", "First Solar", "Technology", "XNAS"),
    ("FTNT", "Fortinet", "Technology", "XNAS"),
    ("FTV", "Fortive", "Industrials", "XNYS"),
    ("GD", "General Dynamics", "Industrials", "XNYS"),
    ("GDDY", "GoDaddy", "Technology", "XNYS"),
    ("GE", "GE Aerospace", "Industrials", "XNYS"),
    ("GEHC", "GE HealthCare", "Healthcare", "XNAS"),
    ("GEN", "Gen Digital", "Technology", "XNAS"),
    ("GEV", "GE Vernova", "Industrials", "XNYS"),
    ("GILD", "Gilead Sciences", "Healthcare", "XNAS"),
    ("GIS", "General Mills", "Consumer Defensive", "XNYS"),
    ("GL", "Globe Life", "Financial Services", "XNYS"),
    ("GLW", "Corning Inc.", "Technology", "XNYS"),
    ("GM", "General Motors", "Consumer Cyclical", "XNYS"),
    ("GNRC", "Generac", "Industrials", "XNYS"),
    ("GOOG", "Alphabet Inc. (Class C)", "Communication", "XNAS"),
    ("GOOGL", "Alphabet Inc. (Class A)", "Communication", "XNAS"),
    ("GPC", "Genuine Parts Company", "Consumer Cyclical", "XNYS"),
    ("GPN", "Global Payments", "Financial Services", "XNYS"),
    ("GRMN", "Garmin", "Consumer Cyclical", "XNYS"),
    ("GS", "Goldman Sachs", "Financial Services", "XNYS"),
    ("GWW", "W. W. Grainger", "Industrials", "XNYS"),
    ("HAL", "Halliburton", "Energy", "XNYS"),
    ("HAS", "Hasbro", "Consumer Cyclical", "XNAS"),
    ("HBAN", "Huntington Bancshares", "Financial Services", "XNAS"),
    ("HCA", "HCA Healthcare", "Healthcare", "XNYS"),
    ("HD", "Home Depot (The)", "Consumer Cyclical", "XNYS"),
    ("HIG", "Hartford (The)", "Financial Services", "XNYS"),
    ("HII", "Huntington Ingalls Industries", "Industrials", "XNYS"),
    ("HLT", "Hilton Worldwide", "Consumer Cyclical", "XNYS"),
    ("HON", "Honeywell Technologies", "Industrials", "XNAS"),
    ("HONA", "Honeywell Aerospace", "Industrials", "XNAS"),
    ("HOOD", "Robinhood Markets", "Financial Services", "XNAS"),
    ("HPE", "Hewlett Packard Enterprise", "Technology", "XNYS"),
    ("HPQ", "HP Inc.", "Technology", "XNYS"),
    ("HRL", "Hormel Foods", "Consumer Defensive", "XNYS"),
    ("HSIC", "Henry Schein", "Healthcare", "XNAS"),
    ("HST", "Host Hotels & Resorts", "Real Estate", "XNAS"),
    ("HSY", "Hershey Company (The)", "Consumer Defensive", "XNYS"),
    ("HUBB", "Hubbell Incorporated", "Industrials", "XNYS"),
    ("HUM", "Humana", "Healthcare", "XNYS"),
    ("HWM", "Howmet Aerospace", "Industrials", "XNYS"),
    ("IBKR", "Interactive Brokers", "Financial Services", "XNAS"),
    ("IBM", "IBM", "Technology", "XNYS"),
    ("ICE", "Intercontinental Exchange", "Financial Services", "XNYS"),
    ("IDXX", "Idexx Laboratories", "Healthcare", "XNAS"),
    ("IEX", "IDEX Corporation", "Industrials", "XNYS"),
    ("IFF", "International Flavors & Fragrances", "Materials", "XNYS"),
    ("INCY", "Incyte", "Healthcare", "XNAS"),
    ("INTC", "Intel", "Technology", "XNAS"),
    ("INTU", "Intuit", "Technology", "XNAS"),
    ("INVH", "Invitation Homes", "Real Estate", "XNYS"),
    ("IP", "International Paper", "Materials", "XNYS"),
    ("IQV", "IQVIA", "Healthcare", "XNYS"),
    ("IR", "Ingersoll Rand", "Industrials", "XNYS"),
    ("IRM", "Iron Mountain", "Real Estate", "XNYS"),
    ("ISRG", "Intuitive Surgical", "Healthcare", "XNAS"),
    ("IT", "Gartner", "Technology", "XNYS"),
    ("ITW", "Illinois Tool Works", "Industrials", "XNYS"),
    ("IVZ", "Invesco", "Financial Services", "XNYS"),
    ("J", "Jacobs Solutions", "Industrials", "XNYS"),
    ("JBHT", "J.B. Hunt", "Industrials", "XNAS"),
    ("JBL", "Jabil", "Technology", "XNYS"),
    ("JCI", "Johnson Controls", "Industrials", "XNYS"),
    ("JKHY", "Jack Henry & Associates", "Financial Services", "XNAS"),
    ("JNJ", "Johnson & Johnson", "Healthcare", "XNYS"),
    ("JPM", "JPMorgan Chase", "Financial Services", "XNYS"),
    ("KDP", "Keurig Dr Pepper", "Consumer Defensive", "XNAS"),
    ("KEY", "KeyCorp", "Financial Services", "XNYS"),
    ("KEYS", "Keysight Technologies", "Technology", "XNYS"),
    ("KHC", "Kraft Heinz", "Consumer Defensive", "XNYS"),
    ("KIM", "Kimco Realty", "Real Estate", "XNYS"),
    ("KKR", "KKR & Co.", "Financial Services", "XNYS"),
    ("KLAC", "KLA Corporation", "Technology", "XNAS"),
    ("KMB", "Kimberly-Clark", "Consumer Defensive", "XNAS"),
    ("KMI", "Kinder Morgan", "Energy", "XNYS"),
    ("KO", "Coca-Cola Company (The)", "Consumer Defensive", "XNYS"),
    ("KR", "Kroger", "Consumer Defensive", "XNYS"),
    ("L", "Loews Corporation", "Financial Services", "XNYS"),
    ("LDOS", "Leidos", "Industrials", "XNYS"),
    ("LEN", "Lennar", "Consumer Cyclical", "XNYS"),
    ("LH", "Labcorp", "Healthcare", "XNYS"),
    ("LHX", "L3Harris", "Industrials", "XNYS"),
    ("LII", "Lennox International", "Industrials", "XNYS"),
    ("LIN", "Linde plc", "Materials", "XNAS"),
    ("LITE", "Lumentum", "Technology", "XNAS"),
    ("LLY", "Lilly (Eli)", "Healthcare", "XNYS"),
    ("LMT", "Lockheed Martin", "Industrials", "XNYS"),
    ("LNT", "Alliant Energy", "Utilities", "XNAS"),
    ("LOW", "Lowe's", "Consumer Cyclical", "XNYS"),
    ("LRCX", "Lam Research", "Technology", "XNAS"),
    ("LULU", "Lululemon Athletica", "Consumer Cyclical", "XNAS"),
    ("LUV", "Southwest Airlines", "Industrials", "XNYS"),
    ("LVS", "Las Vegas Sands", "Consumer Cyclical", "XNYS"),
    ("LYB", "LyondellBasell", "Materials", "XNYS"),
    ("LYV", "Live Nation Entertainment", "Communication", "XNYS"),
    ("MA", "Mastercard", "Financial Services", "XNYS"),
    ("MAA", "Mid-America Apartment Communities", "Real Estate", "XNYS"),
    ("MAR", "Marriott International", "Consumer Cyclical", "XNAS"),
    ("MAS", "Masco", "Industrials", "XNYS"),
    ("MCD", "McDonald's", "Consumer Cyclical", "XNYS"),
    ("MCHP", "Microchip Technology", "Technology", "XNAS"),
    ("MCK", "McKesson Corporation", "Healthcare", "XNYS"),
    ("MCO", "Moody's Corporation", "Financial Services", "XNYS"),
    ("MDLZ", "Mondelez International", "Consumer Defensive", "XNAS"),
    ("MDT", "Medtronic", "Healthcare", "XNYS"),
    ("MET", "MetLife", "Financial Services", "XNYS"),
    ("META", "Meta Platforms", "Communication", "XNAS"),
    ("MGM", "MGM Resorts", "Consumer Cyclical", "XNYS"),
    ("MKC", "McCormick & Company", "Consumer Defensive", "XNYS"),
    ("MLM", "Martin Marietta Materials", "Materials", "XNYS"),
    ("MMM", "3M", "Industrials", "XNYS"),
    ("MNST", "Monster Beverage", "Consumer Defensive", "XNAS"),
    ("MO", "Altria", "Consumer Defensive", "XNYS"),
    ("MOS", "Mosaic Company (The)", "Materials", "XNYS"),
    ("MPC", "Marathon Petroleum", "Energy", "XNYS"),
    ("MPWR", "Monolithic Power Systems", "Technology", "XNAS"),
    ("MRK", "Merck & Co.", "Healthcare", "XNYS"),
    ("MRNA", "Moderna", "Healthcare", "XNAS"),
    ("MRSH", "Marsh McLennan", "Financial Services", "XNYS"),
    ("MRVL", "Marvell Technology", "Technology", "XNAS"),
    ("MS", "Morgan Stanley", "Financial Services", "XNYS"),
    ("MSCI", "MSCI", "Financial Services", "XNYS"),
    ("MSFT", "Microsoft", "Technology", "XNAS"),
    ("MSI", "Motorola Solutions", "Technology", "XNYS"),
    ("MTB", "M&T Bank", "Financial Services", "XNYS"),
    ("MTD", "Mettler Toledo", "Healthcare", "XNYS"),
    ("MU", "Micron Technology", "Technology", "XNAS"),
    ("NCLH", "Norwegian Cruise Line Holdings", "Consumer Cyclical", "XNYS"),
    ("NDAQ", "Nasdaq, Inc.", "Financial Services", "XNAS"),
    ("NDSN", "Nordson Corporation", "Industrials", "XNAS"),
    ("NEE", "NextEra Energy", "Utilities", "XNYS"),
    ("NEM", "Newmont", "Materials", "XNYS"),
    ("NFLX", "Netflix", "Communication", "XNAS"),
    ("NI", "NiSource", "Utilities", "XNYS"),
    ("NKE", "Nike, Inc.", "Consumer Cyclical", "XNYS"),
    ("NOC", "Northrop Grumman", "Industrials", "XNYS"),
    ("NOW", "ServiceNow", "Technology", "XNYS"),
    ("NRG", "NRG Energy", "Utilities", "XNYS"),
    ("NSC", "Norfolk Southern", "Industrials", "XNYS"),
    ("NTAP", "NetApp", "Technology", "XNAS"),
    ("NTRS", "Northern Trust", "Financial Services", "XNAS"),
    ("NUE", "Nucor", "Materials", "XNYS"),
    ("NVDA", "Nvidia", "Technology", "XNAS"),
    ("NVR", "NVR, Inc.", "Consumer Cyclical", "XNYS"),
    ("NWS", "News Corp (Class B)", "Communication", "XNAS"),
    ("NWSA", "News Corp (Class A)", "Communication", "XNAS"),
    ("NXPI", "NXP Semiconductors", "Technology", "XNAS"),
    ("O", "Realty Income", "Real Estate", "XNYS"),
    ("ODFL", "Old Dominion", "Industrials", "XNAS"),
    ("OKE", "Oneok", "Energy", "XNYS"),
    ("OMC", "Omnicom Group", "Communication", "XNYS"),
    ("ON", "ON Semiconductor", "Technology", "XNAS"),
    ("ORCL", "Oracle Corporation", "Technology", "XNYS"),
    ("ORLY", "O'Reilly Automotive", "Consumer Cyclical", "XNAS"),
    ("OTIS", "Otis Worldwide", "Industrials", "XNYS"),
    ("OXY", "Occidental Petroleum", "Energy", "XNYS"),
    ("PANW", "Palo Alto Networks", "Technology", "XNAS"),
    ("PAYX", "Paychex", "Industrials", "XNAS"),
    ("PCAR", "Paccar", "Industrials", "XNAS"),
    ("PCG", "PG&E Corporation", "Utilities", "XNYS"),
    ("PEG", "Public Service Enterprise Group", "Utilities", "XNYS"),
    ("PEP", "PepsiCo", "Consumer Defensive", "XNAS"),
    ("PFE", "Pfizer", "Healthcare", "XNYS"),
    ("PFG", "Principal Financial Group", "Financial Services", "XNAS"),
    ("PG", "Procter & Gamble", "Consumer Defensive", "XNYS"),
    ("PGR", "Progressive Corporation", "Financial Services", "XNYS"),
    ("PH", "Parker Hannifin", "Industrials", "XNYS"),
    ("PHM", "PulteGroup", "Consumer Cyclical", "XNYS"),
    ("PKG", "Packaging Corporation of America", "Materials", "XNYS"),
    ("PLD", "Prologis", "Real Estate", "XNYS"),
    ("PLTR", "Palantir Technologies", "Technology", "XNAS"),
    ("PM", "Philip Morris International", "Consumer Defensive", "XNYS"),
    ("PNC", "PNC Financial Services", "Financial Services", "XNYS"),
    ("PNR", "Pentair", "Industrials", "XNYS"),
    ("PNW", "Pinnacle West Capital", "Utilities", "XNYS"),
    ("PODD", "Insulet Corporation", "Healthcare", "XNAS"),
    ("PPG", "PPG Industries", "Materials", "XNYS"),
    ("PPL", "PPL Corporation", "Utilities", "XNYS"),
    ("PRU", "Prudential Financial", "Financial Services", "XNYS"),
    ("PSA", "Public Storage", "Real Estate", "XNYS"),
    ("PSKY", "Paramount Skydance Corporation", "Communication", "XNAS"),
    ("PSX", "Phillips 66", "Energy", "XNYS"),
    ("PTC", "PTC Inc.", "Technology", "XNAS"),
    ("PWR", "Quanta Services", "Industrials", "XNYS"),
    ("PYPL", "PayPal", "Financial Services", "XNAS"),
    ("Q", "Qnity Electronics", "Technology", "XNYS"),
    ("QCOM", "Qualcomm", "Technology", "XNAS"),
    ("RCL", "Royal Caribbean Group", "Consumer Cyclical", "XNYS"),
    ("RDDT", "Reddit", "Communication", "XNYS"),
    ("REG", "Regency Centers", "Real Estate", "XNAS"),
    ("REGN", "Regeneron Pharmaceuticals", "Healthcare", "XNAS"),
    ("RF", "Regions Financial Corporation", "Financial Services", "XNYS"),
    ("RJF", "Raymond James Financial", "Financial Services", "XNYS"),
    ("RL", "Ralph Lauren Corporation", "Consumer Cyclical", "XNYS"),
    ("RMD", "ResMed|", "Healthcare", "XNYS"),
    ("ROK", "Rockwell Automation", "Industrials", "XNYS"),
    ("ROL", "Rollins, Inc.", "Industrials", "XNYS"),
    ("ROP", "Roper Technologies", "Technology", "XNAS"),
    ("ROST", "Ross Stores", "Consumer Cyclical", "XNAS"),
    ("RSG", "Republic Services", "Industrials", "XNYS"),
    ("RTX", "RTX Corporation", "Industrials", "XNYS"),
    ("RVTY", "Revvity", "Healthcare", "XNYS"),
    ("SBAC", "SBA Communications", "Real Estate", "XNAS"),
    ("SBUX", "Starbucks", "Consumer Cyclical", "XNAS"),
    ("SCHW", "Charles Schwab Corporation", "Financial Services", "XNYS"),
    ("SHW", "Sherwin-Williams", "Materials", "XNYS"),
    ("SJM", "J.M. Smucker Company (The)", "Consumer Defensive", "XNYS"),
    ("SLB", "Schlumberger", "Energy", "XNYS"),
    ("SMCI", "Supermicro", "Technology", "XNAS"),
    ("SNA", "Snap-on", "Industrials", "XNYS"),
    ("SNDK", "Sandisk", "Technology", "XNAS"),
    ("SNPS", "Synopsys", "Technology", "XNAS"),
    ("SO", "Southern Company", "Utilities", "XNYS"),
    ("SOLV", "Solventum", "Healthcare", "XNYS"),
    ("SPG", "Simon Property Group", "Real Estate", "XNYS"),
    ("SPGI", "S&P Global", "Financial Services", "XNYS"),
    ("SRE", "Sempra", "Utilities", "XNYS"),
    ("STE", "Steris", "Healthcare", "XNYS"),
    ("STLD", "Steel Dynamics", "Materials", "XNAS"),
    ("STT", "State Street Corporation", "Financial Services", "XNYS"),
    ("STX", "Seagate Technology", "Technology", "XNAS"),
    ("STZ", "Constellation Brands", "Consumer Defensive", "XNYS"),
    ("SW", "Smurfit Westrock", "Materials", "XNYS"),
    ("SWK", "Stanley Black & Decker", "Industrials", "XNYS"),
    ("SWKS", "Skyworks Solutions", "Technology", "XNAS"),
    ("SYF", "Synchrony Financial", "Financial Services", "XNYS"),
    ("SYK", "Stryker Corporation", "Healthcare", "XNYS"),
    ("SYY", "Sysco", "Consumer Defensive", "XNYS"),
    ("T", "AT&T", "Communication", "XNYS"),
    ("TAP", "Molson Coors Beverage Company", "Consumer Defensive", "XNYS"),
    ("TDG", "TransDigm Group", "Industrials", "XNYS"),
    ("TDY", "Teledyne Technologies", "Technology", "XNYS"),
    ("TECH", "Bio-Techne", "Healthcare", "XNAS"),
    ("TEL", "TE Connectivity", "Technology", "XNYS"),
    ("TER", "Teradyne", "Technology", "XNAS"),
    ("TFC", "Truist Financial", "Financial Services", "XNYS"),
    ("TGT", "Target Corporation", "Consumer Defensive", "XNYS"),
    ("TJX", "TJX Companies", "Consumer Cyclical", "XNYS"),
    ("TKO", "TKO Group Holdings", "Communication", "XNYS"),
    ("TMO", "Thermo Fisher Scientific", "Healthcare", "XNYS"),
    ("TMUS", "T-Mobile US", "Communication", "XNAS"),
    ("TPL", "Texas Pacific Land Corporation", "Energy", "XNYS"),
    ("TPR", "Tapestry, Inc.", "Consumer Cyclical", "XNYS"),
    ("TRGP", "Targa Resources", "Energy", "XNYS"),
    ("TRMB", "Trimble Inc.", "Technology", "XNAS"),
    ("TROW", "T. Rowe Price", "Financial Services", "XNAS"),
    ("TRV", "Travelers Companies (The)", "Financial Services", "XNYS"),
    ("TSCO", "Tractor Supply", "Consumer Cyclical", "XNAS"),
    ("TSLA", "Tesla, Inc.", "Consumer Cyclical", "XNAS"),
    ("TSN", "Tyson Foods", "Consumer Defensive", "XNYS"),
    ("TT", "Trane Technologies", "Industrials", "XNYS"),
    ("TTD", "Trade Desk (The)", "Communication", "XNAS"),
    ("TTWO", "Take-Two Interactive", "Communication", "XNAS"),
    ("TXN", "Texas Instruments", "Technology", "XNAS"),
    ("TXT", "Textron", "Industrials", "XNYS"),
    ("TYL", "Tyler Technologies", "Technology", "XNYS"),
    ("UAL", "United Airlines Holdings", "Industrials", "XNAS"),
    ("UBER", "Uber", "Industrials", "XNYS"),
    ("UDR", "UDR, Inc.", "Real Estate", "XNYS"),
    ("UHS", "Universal Health Services", "Healthcare", "XNYS"),
    ("ULTA", "Ulta Beauty", "Consumer Cyclical", "XNAS"),
    ("UNH", "UnitedHealth Group", "Healthcare", "XNYS"),
    ("UNP", "Union Pacific Corporation", "Industrials", "XNYS"),
    ("UPS", "United Parcel Service", "Industrials", "XNYS"),
    ("URI", "United Rentals", "Industrials", "XNYS"),
    ("USB", "U.S. Bancorp", "Financial Services", "XNYS"),
    ("V", "Visa Inc.", "Financial Services", "XNYS"),
    ("VEEV", "Veeva Systems", "Healthcare", "XNYS"),
    ("VICI", "Vici Properties", "Real Estate", "XNYS"),
    ("VLO", "Valero Energy", "Energy", "XNYS"),
    ("VLTO", "Veralto", "Industrials", "XNYS"),
    ("VMC", "Vulcan Materials Company", "Materials", "XNYS"),
    ("VMRK", "Vivmark Residential", "Real Estate", "XNYS"),
    ("VRSK", "Verisk Analytics", "Industrials", "XNAS"),
    ("VRSN", "Verisign", "Technology", "XNAS"),
    ("VRT", "Vertiv", "Industrials", "XNYS"),
    ("VRTX", "Vertex Pharmaceuticals", "Healthcare", "XNAS"),
    ("VST", "Vistra Corp.", "Utilities", "XNYS"),
    ("VTR", "Ventas", "Real Estate", "XNYS"),
    ("VTRS", "Viatris", "Healthcare", "XNAS"),
    ("VZ", "Verizon", "Communication", "XNYS"),
    ("WAB", "Wabtec", "Industrials", "XNYS"),
    ("WAT", "Waters Corporation", "Healthcare", "XNYS"),
    ("WBD", "Warner Bros. Discovery", "Communication", "XNAS"),
    ("WDAY", "Workday, Inc.", "Technology", "XNAS"),
    ("WDC", "Western Digital", "Technology", "XNAS"),
    ("WEC", "WEC Energy Group", "Utilities", "XNYS"),
    ("WELL", "Welltower", "Real Estate", "XNYS"),
    ("WFC", "Wells Fargo", "Financial Services", "XNYS"),
    ("WM", "Waste Management", "Industrials", "XNYS"),
    ("WMB", "Williams Companies", "Energy", "XNYS"),
    ("WMT", "Walmart", "Consumer Defensive", "XNAS"),
    ("WRB", "W. R. Berkley Corporation", "Financial Services", "XNYS"),
    ("WSM", "Williams-Sonoma, Inc.", "Consumer Cyclical", "XNYS"),
    ("WST", "West Pharmaceutical Services", "Healthcare", "XNYS"),
    ("WTW", "Willis Towers Watson", "Financial Services", "XNAS"),
    ("WY", "Weyerhaeuser", "Real Estate", "XNYS"),
    ("WYNN", "Wynn Resorts", "Consumer Cyclical", "XNAS"),
    ("XEL", "Xcel Energy", "Utilities", "XNAS"),
    ("XOM", "ExxonMobil", "Energy", "XNYS"),
    ("XYL", "Xylem Inc.", "Industrials", "XNYS"),
    ("XYZ", "Block, Inc.", "Financial Services", "XNYS"),
    ("YUM", "Yum! Brands", "Consumer Cyclical", "XNYS"),
    ("ZBH", "Zimmer Biomet", "Healthcare", "XNYS"),
    ("ZBRA", "Zebra Technologies", "Technology", "XNAS"),
    ("ZTS", "Zoetis", "Healthcare", "XNYS"),
]

SP500_SYMBOLS: frozenset[str] = frozenset(s for s, _, _, _ in SP500_MEMBERS)
